<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password_fe</name>
   <tag></tag>
   <elementGuidId>3987be1c-4b58-4295-89ca-2cf0e6394d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;styles__HeaderWrapper-sc-1cpcgf0-0 hUJbir&quot;]/div[@class=&quot;styles__ContainerWrapper-sc-1cpcgf0-1 kdkWci&quot;]/div[@class=&quot;styles__LoginWrapper-sc-1n50m2z-0 bIFgQd&quot;]/div[@class=&quot;right-sidebar-root&quot;]/div[@class=&quot;right-sidebar-content&quot;]/form[@class=&quot;sc-bxivhb gVGlWJ&quot;]/div[@class=&quot;sc-ifAKCX kfilsK position-relative form-group&quot;]/input[@class=&quot;sc-EHOje cnhJKu form-control&quot;][count(. | //input[@name = 'password' and @placeholder = 'Password' and @type = 'password' and @class = 'sc-EHOje cnhJKu form-control']) = count(//input[@name = 'password' and @placeholder = 'Password' and @type = 'password' and @class = 'sc-EHOje cnhJKu form-control'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-EHOje cnhJKu form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;styles__HeaderWrapper-sc-1cpcgf0-0 hUJbir&quot;]/div[@class=&quot;styles__ContainerWrapper-sc-1cpcgf0-1 kdkWci&quot;]/div[@class=&quot;styles__LoginWrapper-sc-1n50m2z-0 bIFgQd&quot;]/div[@class=&quot;right-sidebar-root&quot;]/div[@class=&quot;right-sidebar-content&quot;]/form[@class=&quot;sc-bxivhb gVGlWJ&quot;]/div[@class=&quot;sc-ifAKCX kfilsK position-relative form-group&quot;]/input[@class=&quot;sc-EHOje cnhJKu form-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//input[@name='password']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/form/div/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//input[2]</value>
   </webElementXpaths>
</WebElementEntity>
